apiVersion: batch/v1
kind: Job
metadata:
  name: k6
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: k6
          image: "perfana/k6-afterburner:1.0.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: K6_INFLUXDB_URL
              valueFrom:
                secretKeyRef:
                  name: k6-args
                  key: K6_INFLUXDB_URL
            - name: K6_INFLUXDB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: k6-args
                  key: K6_INFLUXDB_USERNAME
            - name: K6_INFLUXDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: k6-args
                  key: K6_INFLUXDB_PASSWORD
            - name: CONSTANT_LOAD_TIME
              valueFrom:
                secretKeyRef:
                  name: k6-args
                  key: CONSTANT_LOAD_TIME
            - name: RAMPUP_TIME
              valueFrom:
                secretKeyRef:
                  name: k6-args
                  key: RAMPUP_TIME
            - name: START_RATE
              valueFrom:
                secretKeyRef:
                  name: k6-args
                  key: START_RATE
            - name: TARGET_RATE
              valueFrom:
                secretKeyRef:
                  name: k6-args
                  key: TARGET_RATE
            - name: TARGET_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: k6-args
                  key: TARGET_BASE_URL
            - name: SYSTEM_UNDER_TEST
              valueFrom:
                secretKeyRef:
                  name: k6-args
                  key: SYSTEM_UNDER_TEST
            - name: TEST_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: k6-args
                  key: TEST_ENVIRONMENT
            - name: TEST_RUN_ID
              valueFrom:
                secretKeyRef:
                  name: k6-args
                  key: TEST_RUN_ID

          args:
            - "run"
            - "/home/k6/script.js"
            - "-out"
            - "influxdb=$(K6_INFLUXDB_URL)"
            - "-e"
            - "K6_INFLUXDB_USERNAME=$(K6_INFLUXDB_USERNAME)"
            - "-e"
            - "K6_INFLUXDB_PASSWORD=$(K6_INFLUXDB_PASSWORD)"
            - "-e"
            - "CONSTANT_LOAD_TIME=$(CONSTANT_LOAD_TIME)"
            - "-e"
            - "RAMPUP_TIME=$(RAMPUP_TIME)"
            - "-e"
            - "START_RATE=$(START_RATE)"
            - "-e"
            - "TARGET_RATE=$(TARGET_RATE)"
            - "-e"
            - "TARGET_BASE_URL=$(TARGET_BASE_URL)"
            - "-e"
            - "SYSTEM_UNDER_TEST=$(SYSTEM_UNDER_TEST)"
            - "-e"
            - "TEST_ENVIRONMENT=$(TEST_ENVIRONMENT)"
            - "-e"
            - "TEST_RUN_ID=$(TEST_RUN_ID)"