---
name: Run performance tests with Gatling docker container

on:
  workflow_call:
    inputs:
      systemUnderTest:
        required: true
        type: string
      workload:
        required: true
        type: string
      service:
        required: true
        type: string
      annotations:
        required: false
        type: string


jobs:

  performance-test-gatling-docker:
    runs-on: [self-hosted, demo]
    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        id: install
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout afterburner repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get commit message
        if: inputs.annotations == ''
        run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")" >> $GITHUB_ENV
      - name: get KUBECONFIG from secrets
        env:
          KUBECONFIG_TO_FILE: ${{secrets.KUBECONFIG_ACME}}
        run: echo "$KUBECONFIG_TO_FILE" | base64 --decode --ignore-garbage >> /runner/_work/afterburner/afterburner/config
      - name: Get deployed version
        if: env.TAG_NAME == ''
        env:
          KUBECONFIG: /runner/_work/afterburner/afterburner/config
        run: |
          VERSION=$(kubectl get deployment ${{ inputs.service }}-fe-afterburner -n acme -o jsonpath='{$.spec.template.spec.containers[:1].image}' | cut -d ":" -f 2) 
          echo "TAG_NAME=$VERSION" >> $GITHUB_ENV
      - name: get KUBECONFIG from secrets
        env:
          KUBECONFIG_TO_FILE: ${{secrets.KUBECONFIG_ACME}}
        run: echo "$KUBECONFIG_TO_FILE" | base64 --decode --ignore-garbage >> /runner/_work/afterburner/afterburner/config
      - name: Build with Maven
        env:
          KUBECONFIG: /runner/_work/afterburner/afterburner/config
        run: |
          cd cicd/gatling
          mvn clean install -U event-scheduler:test -Ptest-env-demo,test-type-${{ inputs.workload }},assert-results -f pom-k8s-job.xml \
          -Dsut-config=${{ inputs.service }} \
          -DtestRunId="${{ inputs.systemUnderTest }}-${{ github.job }}-${{ github.run_number }}-2" \
          -DbuildResultsUrl="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          -Dversion="${{ env.TAG_NAME }}" \
          -DsystemUnderTest=${{ inputs.systemUnderTest }} \
          -DtestEnvironment=acme \
          -Dannotations="$COMMIT_MESSAGE" \
          -DapiKey=${{ secrets.PERFANA_APIKEY }} \
          -DtargetBaseUrl=http://${{ inputs.service }}-fe-afterburner.acme:8080 \
          -DinfluxUrl=https://influx.demo.perfana.cloud \
          -DinfluxUser=admin \
          -DinfluxPassword=${{ secrets.INFLUXDB_PASSWORD }} \
          -DelasticPassword=${{ secrets.ELASTIC_PASSWORD }} \
          -DperfanaUrl=https://demo.perfana.cloud
